version: '3'
services:
        spring-boot-app:
                build:
                        context: .
                        dockerfile: Dockerfile
                image: dream-back
                container_name: dream-back
                ports:
                        - "9090:9090"
