version: '3'
services:
        react-app:
                build:
                        context: .
                        dockerfile: Dockerfile
                image: dream-front
                container_name: dream-front
                ports:
                        - "3000:3000"
